version: "3.8"

services:
  web:
    container_name: golang-web
    build: .
    ports:
      - "3001:3001"
    restart: "always"
    networks:
      - "web.network"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
  db:
    container_name: db-postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - "web.network"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  nginx:
    container_name: server-nginx
    image: nginx:latest
    volumes:
      - staticdata:/usr/src/app/public/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "80:80"
    networks:
      - "web.network"
    restart: "always"
networks:
  web.network:
volumes:
  staticdata:
  postgres-db: